steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_IMAGE_URL'
      - '-f'
      - 'remote/Dockerfile.runtime'
      - '.'

images:
  - '$_IMAGE_URL'

substitutions:
  _IMAGE_URL: 'gcr.io/${PROJECT_ID}/agent-backend-remote:latest'
